using Cysharp.Threading.Tasks;
using System.Collections.Generic;
using System.Threading;
using UnityEngine;
using UnityEngine.Events;
using VTNConnect;

namespace Game
{
    public class GameManager : MonoBehaviour
    {
        public static event UnityAction OnGameStart;
        public static event UnityAction OnGameEnd;

        AdventurerSpawner _spawner;
        int _resultCount;

        void Awake()
        {
            _spawner = AdventurerSpawner.Find();
        }

        void Start()
        {
            UpdateAsync(this.GetCancellationTokenOnDestroy()).Forget();
        }

        void OnDestroy()
        {
            OnGameStart = null;
            OnGameEnd = null;

            VantanConnect.GameEnd().Forget();
            VantanConnect.SystemReset();
        }

        // –`Œ¯Ò‚ª’Eo‚âŒ‚”j‚³‚ê‚½ê‡A–`Œ¯Ò‘¤‚©‚çŒÄ‚Ño‚µ‚Ä–`Œ¯‚ÌŒ‹‰Ê‚ğ•ñ‚·‚éB
        public static void SetAdventureResult(int userID, bool isEscape, bool isSubGoalClear)
        {
            VantanConnect.UserRecord(userID, isEscape, isSubGoalClear);

            GameManager gameManager = GameObject.FindGameObjectWithTag("GameManager").GetComponent<GameManager>();
            gameManager._resultCount++;
        }

        async UniTask UpdateAsync(CancellationToken token)
        {
            while (!token.IsCancellationRequested)
            {
                // ƒQ[ƒ€ŠJnB
                GameStartAIGameResult gameStartResult = await VantanConnect.GameStart();
                token.ThrowIfCancellationRequested();
                OnGameStart?.Invoke();

                _resultCount = 0;

                // ˆê’èŠÔŠu‚Å–`Œ¯Ò‚ğ¶¬B
                int spawnedCount = await _spawner.SpawnAsync(gameStartResult.Artifacts, token);

                // ¶¬‚µ‚½–`Œ¯Ò‚ª‘SˆõA–`Œ¯‚ÌŒ‹‰Ê‚ğ•ñ‚·‚é‚Ü‚Å‘Ò‚ÂB
                await UniTask.WaitUntil(() => _resultCount == spawnedCount, cancellationToken: token);

                // ƒQ[ƒ€I—¹B
                await VantanConnect.GameEnd();
                token.ThrowIfCancellationRequested();
                OnGameEnd?.Invoke();

                VantanConnect.SystemReset();
            }
        }
    }
}